# Generated by Django 3.0.6 on 2020-05-12 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.IntegerField()),
                ('nama', models.CharField(max_length=255, null=True)),
                ('foto', models.ImageField(null=True, upload_to='character')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=255, null=True)),
                ('judul', models.CharField(max_length=255)),
                ('judul_alternatif', models.CharField(max_length=255, null=True)),
                ('musim_rilis', models.CharField(max_length=255, null=True)),
                ('jumlah_episode', models.IntegerField(default=0)),
                ('mulai_tayang', models.CharField(max_length=255, null=True)),
                ('selesai_tayang', models.CharField(max_length=255, null=True)),
                ('studio', models.CharField(max_length=255, null=True)),
                ('rating', models.FloatField(null=True)),
                ('credit', models.TextField(blank=True, null=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('gambar', models.ImageField(null=True, upload_to='gambar')),
                ('tanggal_post', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(choices=[('o', 'ongoing'), ('c', 'complete'), ('m', 'movie')], max_length=1)),
                ('genre', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('admin', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.IntegerField()),
                ('judul_link', models.TextField(blank=True, null=True)),
                ('url1080p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('url720p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('url540p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('url480p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('url360p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
                ('url240p', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None)),
            ],
        ),
    ]
