# Generated by Django 2.2.1 on 2019-05-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_film', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
