# Generated by Django 2.2.1 on 2019-06-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_film'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='judul_film',
            new_name='judul',
        ),
        migrations.AddField(
            model_name='film',
            name='credit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='judul_alternatif',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='jumlah_episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='kode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='musim_rilis',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='selesai_tayang',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='studio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='tanggal_tayang',
            field=models.DateTimeField(null=True),
        ),
    ]
