# Generated by Django 2.2.1 on 2019-06-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20190601_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='selesai_tayang',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='tanggal_tayang',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
