# Generated by Django 2.2.1 on 2019-06-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_auto_20190601_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='tanggal_tayang',
            new_name='mulai_tayang',
        ),
    ]
