# Generated by Django 2.2.1 on 2019-06-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20190601_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='gambar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
