# Generated by Django 2.2.1 on 2019-06-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20190601_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='gambar',
            field=models.ImageField(null=True, upload_to='gambar'),
        ),
    ]
