# Generated by Django 2.2.1 on 2019-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_film_tanggal_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.IntegerField()),
                ('judul_link', models.TextField(blank=True, null=True)),
                ('url1080p', models.TextField(blank=True, null=True)),
                ('url720p', models.TextField(blank=True, null=True)),
                ('url540p', models.TextField(blank=True, null=True)),
                ('url360p', models.TextField(blank=True, null=True)),
                ('url240p', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
