# Generated by Django 2.2.1 on 2019-06-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_linkdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdownload',
            name='url480p',
            field=models.TextField(blank=True, null=True),
        ),
    ]
