# Generated by Django 2.2.1 on 2019-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_linkdownload_url480p'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_film', models.IntegerField()),
                ('nama', models.CharField(max_length=255, null=True)),
                ('foto', models.ImageField(null=True, upload_to='character')),
            ],
        ),
    ]
