# Generated by Django 2.2.1 on 2019-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='jenis',
            field=models.CharField(default='complete', max_length=50),
        ),
    ]
