# Generated by Django 2.2.1 on 2019-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0013_film_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='jenis',
            field=models.CharField(choices=[('o', 'ongoing'), ('c', 'complete'), ('m', 'movie')], max_length=1),
        ),
    ]
