# Generated by Django 2.2.1 on 2019-06-11 17:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_auto_20190610_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
