# Generated by Django 2.2.1 on 2019-06-19 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0015_film_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkdownload',
            name='url1080p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='url240p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='url360p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='url480p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='url540p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='linkdownload',
            name='url720p',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=None),
        ),
    ]
